---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/builder-task}

params:
  REPOSITORY: cirocosta/estaleiro
  TAG: latest
  CONTEXT: repository

inputs:
- name: repository

outputs:
- name: image

run: {path: build}
