platform: linux

params:
  FILENAME: ~

inputs: 
  - name: rc-image
  - name: repository
    path: .

outputs:
  - name: image

run:
  path: /bin/sh
  args:
    - -cex
    - |
      stty columns 80
      sanitize-cgroups

      buildctl-daemonless.sh build \
          --frontend gateway.v0 \
          --local context=./samples \
          --local dockerfile=./samples \
          --opt filename=./$FILENAME \
          --opt source=cirocosta/estaleiro@$(cat ./rc-image/digest) \
          --progress plain \
          --output type=docker,dest=image/image.tar
