resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource


resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/estaleiro
      ignore_paths: [ ./VERSION ]

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/estaleiro
      tag: rc
      username: ((docker-user))
      password: ((docker-password))

  - name: image-buildkit
    type: registry-image
    source:
      repository: cirocosta/buildkit-task


jobs:
  - name: build
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true}
            - {get: image-buildkit, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: repository
              path: .
          outputs:
            - name: image
          run:
            path: /bin/sh
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro \
                    --opt build-arg:estaleiro-commit=$(git rev-parse HEAD) \
                    --local dockerfile=. \
                    --local context=. \
                    --output type=oci,dest=image/image.tar
      - put: container-image
        inputs: [image]
        get_params: {format: oci}
        params:
          image: image/image.tar
