jobs:
  - name: build-image
    public: true
    plan:
      - {get: repository, trigger: true}
      - task: build-image
        privileged: true
        params: {TARGET: "frontend"}
        file: repository/ci/tasks/build.yml
      - put: container-image
        inputs: [image]
        get_params: {format: oci}
        params:
          image: image/image.tar


  - name: estaleiro
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true}
            - {get: container-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: container-image
            - name: repository
              path: .
          run:
            path: /bin/sh
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro@$(cat ./container-image/digest) \
                    --opt build-arg:estaleiro-commit=$(git rev-parse HEAD) \
                    --local dockerfile=. \
                    --local context=.


  - name: s3-resource
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true}
            - {get: container-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
            - {get: s3-resource, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: container-image
            - name: repository
              path: .
            - name: s3-resource
              path: samples/s3-resource
          run:
            path: /bin/sh
            dir: samples
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro@$(cat ../container-image/digest) \
                    --opt filename=s3-resource.hcl \
                    --opt build-arg:ref=$(cd ./s3-resource && git rev-parse HEAD) \
                    --local context=. \
                    --local dockerfile=.


  - name: git-resource
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true}
            - {get: container-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
            - {get: git-resource, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: container-image
            - name: repository
              path: .
            - name: git-resource
              path: samples/git-resource
          run:
            path: /bin/sh
            dir: samples
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                tar czvf assets.tgz -C ./git-resource/assets .

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro@$(cat ../container-image/digest) \
                    --opt filename=git-resource.hcl \
                    --opt build-arg:ref=$(cd ./git-resource && git rev-parse HEAD) \
                    --local context=. \
                    --local dockerfile=.


resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource



resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/estaleiro
      ignore_paths: [ ./VERSION ]

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/estaleiro
      tag: rc
      username: ((docker-user))
      password: ((docker-password))

  - name: image-buildkit
    type: registry-image
    source:
      repository: cirocosta/buildkit-task


  - name: s3-resource
    type: git
    source:
      uri: https://github.com/concourse/s3-resource

  - name: git-resource
    type: git
    source:
      uri: https://github.com/concourse/git-resource
