resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource


resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/estaleiro
      ignore_paths: [ ./VERSION ]

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/estaleiro
      tag: rc
      username: ((docker-user))
      password: ((docker-password))

  - name: container-image-frontend
    type: registry-image
    source:
      repository: cirocosta/estaleiro-frontend
      tag: rc
      username: ((docker-user))
      password: ((docker-password))

  - name: image-buildkit
    type: registry-image
    source:
      repository: cirocosta/buildkit-task


jobs:
  - name: build
    public: true
    plan:
      - {get: repository, trigger: true}
      - in_parallel:
          fail_fast: true
          steps:
            - task: build-regular
              file: repository/ci/tasks/build-with-rootfs.yml
              params: {TARGET: "release"}
              privileged: true
            - task: build-frontend
              file: repository/ci/tasks/build.yml
              output_mapping: { image: image-frontend }
              params: {TARGET: "frontend"}
              privileged: true
            - task: test
              file: repository/ci/tasks/build.yml
              output_mapping: { image: discard }
              params: {TARGET: "test"}
              privileged: true
            - {get: image-buildkit, trigger: true}
      - task: integration
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: rootfs
            - name: repository
          run:
            path: /bin/sh
            args:
              - -cex
              - |
                export PATH=$(realpath ./rootfs)/rootfs/usr/local/bin:$PATH

                stty columns 80
                sanitize-cgroups

                cd ./repository
                estaleiro build -f ./estaleiro.hcl | buildctl-daemonless.sh build --local context=.
      - in_parallel:
          fail_fast: true
          steps:
            - put: container-image
              inputs: [image]
              get_params: {format: oci}
              params:
                image: image/image.tar
            - put: container-image-frontend
              inputs: [image-frontend]
              get_params: {format: oci}
              params:
                image: image-frontend/image.tar

