
jobs:
  - name: estaleiro
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true}
            - {get: container-image, trigger: true}
            - {get: image-buildkit, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: repository
              path: .
          run:
            path: /bin/sh
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro \
                    --opt build-arg:estaleiro-commit=$(git rev-parse HEAD) \
                    --local dockerfile=. \
                    --local context=.


  - name: s3-resource
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true}
            - {get: container-image, trigger: true}
            - {get: image-buildkit, trigger: true}
            - {get: s3-resource, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: repository
              path: .
            - name: s3-resource
              path: samples/concourse/s3-resource
          run:
            path: /bin/sh
            dir: samples/concourse
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                pwd
                ls

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro \
                    --opt filename=s3-resource.hcl \
                    --opt build-arg:ref=$(cd ./s3-resource && git rev-parse HEAD) \
                    --local context=. \
                    --local dockerfile=.



resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource



resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/estaleiro
      ignore_paths: [ ./VERSION ]

  - name: container-image
    type: registry-image
    source:
      repository: cirocosta/estaleiro

  - name: image-buildkit
    type: registry-image
    source:
      repository: cirocosta/buildkit-task


  - name: s3-resource
    type: git
    source:
      uri: https://github.com/concourse/s3-resource

