jobs:
  - name: build-image
    public: true
    plan:
      - {get: repository, trigger: true}
      - task: build-image
        privileged: true
        params: {TARGET: "frontend"}
        file: repository/ci/tasks/build.yml
      - put: rc-image
        inputs: [image]
        get_params: {format: oci}
        params:
          image: image/image.tar


  - name: estaleiro
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true, passed: [build-image]}
            - {get: rc-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: rc-image
            - name: repository
              path: .
          outputs:
            - name: image
          run:
            path: /bin/sh
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro@$(cat ./rc-image/digest) \
                    --opt build-arg:estaleiro-commit=$(git rev-parse HEAD) \
                    --local dockerfile=. \
                    --local context=. \
                    --output type=docker,dest=image/image.tar
      - in_parallel:
          steps:
            - task: read-bom
              file: ./repository/ci/tasks/read-bom.yml
            - put: test-image
              inputs: [image]
              get_params: {format: oci}
              params:
                image: image/image.tar



  - name: scratch
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true, passed: [build-image]}
            - {get: rc-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: rc-image
            - name: repository
              path: .
          outputs:
            - name: image
          run:
            path: /bin/sh
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --frontend gateway.v0 \
                    --local context=. \
                    --local dockerfile=. \
                    --opt filename=scratch.hcl \
                    --opt source=cirocosta/estaleiro@$(cat ./rc-image/digest) \
                    --progress plain \
                    --output type=docker,dest=image/image.tar
      - in_parallel:
          steps:
            - task: read-bom
              file: ./repository/ci/tasks/read-bom.yml
            - put: scratch-image
              inputs: [image]
              get_params: {format: oci}
              params:
                image: image/image.tar


  - name: s3-resource
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true, passed: [build-image]}
            - {get: rc-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
            - {get: s3-resource, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: rc-image
            - name: repository
              path: .
            - name: s3-resource
              path: samples/s3-resource
          outputs:
            - name: image
              path: samples/image
          run:
            path: /bin/sh
            dir: samples
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro@$(cat ../rc-image/digest) \
                    --opt filename=s3-resource.hcl \
                    --opt build-arg:ref=$(cd ./s3-resource && git rev-parse HEAD) \
                    --local context=. \
                    --local dockerfile=. \
                    --output type=docker,dest=image/image.tar
      - in_parallel:
          steps:
            - task: read-bom
              file: ./repository/ci/tasks/read-bom.yml
            - put: s3-resource-image
              inputs: [image]
              get_params: {format: oci}
              params:
                image: image/image.tar


  - name: git-resource
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true, passed: [build-image]}
            - {get: rc-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
            - {get: git-resource, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: rc-image
            - name: repository
              path: .
            - name: git-resource
              path: samples/git-resource
          outputs:
            - name: image
              path: samples/image
          run:
            path: /bin/sh
            dir: samples
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                tar czvf assets.tgz -C ./git-resource/assets .

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro@$(cat ../rc-image/digest) \
                    --opt filename=git-resource.hcl \
                    --opt build-arg:ref=$(cd ./git-resource && git rev-parse HEAD) \
                    --local context=. \
                    --local dockerfile=. \
                    --output type=docker,dest=image/image.tar
      - in_parallel:
          steps:
            - task: read-bom
              file: ./repository/ci/tasks/read-bom.yml
            - put: git-resource-image
              inputs: [image]
              get_params: {format: oci}
              params:
                image: image/image.tar


  - name: docker-image-resource
    public: true
    plan:
      - in_parallel:
          steps:
            - {get: repository, trigger: true, passed: [build-image]}
            - {get: rc-image, trigger: true, passed: [build-image]}
            - {get: image-buildkit, trigger: true}
            - {get: docker-image-resource, trigger: true}
      - task: build
        image: image-buildkit
        privileged: true
        config:
          platform: linux
          inputs: 
            - name: rc-image
            - name: repository
              path: .
            - name: docker-image-resource
              path: samples/docker-image-resource
          outputs:
            - name: image
              path: samples/image
          run:
            path: /bin/sh
            dir: samples
            args:
              - -cex
              - |
                stty columns 80
                sanitize-cgroups

                buildctl-daemonless.sh build \
                    --progress plain \
                    --frontend gateway.v0 \
                    --opt source=cirocosta/estaleiro@$(cat ../rc-image/digest) \
                    --opt filename=docker-image-resource.hcl \
                    --opt build-arg:ref=$(cd ./docker-image-resource && git rev-parse HEAD) \
                    --local context=. \
                    --local dockerfile=. \
                    --output type=docker,dest=image/image.tar
      - in_parallel:
          steps:
            - task: read-bom
              file: ./repository/ci/tasks/read-bom.yml
            - put: docker-image-resource-image
              inputs: [image]
              get_params: {format: oci}
              params:
                image: image/image.tar



resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource



resources:
  - name: repository
    type: git
    source:
      uri: https://((github-token))@github.com/cirocosta/estaleiro
      ignore_paths: [ ./VERSION ]

  - name: rc-image
    type: registry-image
    source:
      repository: cirocosta/estaleiro
      tag: rc
      username: ((docker-user))
      password: ((docker-password))

  - name: test-image
    type: registry-image
    source:
      repository: registry-docker-registry.registry.svc.cluster.local:5000/estaleiro

  - name: image-buildkit
    type: registry-image
    source:
      repository: cirocosta/buildkit-task

  - name: s3-resource
    type: git
    source:
      uri: https://github.com/concourse/s3-resource

  - name: s3-resource-image
    type: registry-image
    source:
      repository: registry-docker-registry.registry.svc.cluster.local:5000/s3-resource

  - name: git-resource
    type: git
    source:
      uri: https://github.com/concourse/git-resource

  - name: git-resource-image
    type: registry-image
    source:
      repository: registry-docker-registry.registry.svc.cluster.local:5000/git-resource

  - name: docker-image-resource
    type: git
    source:
      uri: https://github.com/concourse/docker-image-resource

  - name: docker-image-resource-image
    type: registry-image
    source:
      repository: registry-docker-registry.registry.svc.cluster.local:5000/docker-image-resource

  - name: scratch-image
    type: registry-image
    source:
      repository: registry-docker-registry.registry.svc.cluster.local:5000/scratch
